Blog/urls.py
from django.urls import path,include
from . import views

app_name = 'Blog'

urlpatterns = [
    path('',views.blog,name='blog'),

    path('blog/<slug>/',views.blog_details,name='blog_details')
]

myapp/urls.py
from django.urls import path,include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('',views.homepage,name='homepage')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls',namespace='myapp')),
    path('blog/',include('Blog.urls',namespace='Blog')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

Blog/models.py
from django.db import models
from django.urls import reverse 

# Create your models here.
class Post(models.Model):
    thumbnail = models.ImageField(upload_to='post/photo')
    title = models.CharField(default=None, max_length=200)
    short_description = models.TextField(default=None)
    slug = models.SlugField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Blog:blog_details",kwargs={'slug':self.slug})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='commennts' )
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

myapp/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    address = models.TextField()
    image = models.ImageField(upload_to='profile\photos')
    created_at = models.DateTimeField(auto_now_add=True)

Blog/forms.py
from django import  forms
from .models import Comment

class CommentForm():
    class Meta:
        model= Comment
        fields=('name','body')

Blog/views.py
from django.shortcuts import render
from .forms import CommentForm
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import redirect 
from .models import Post


# Create your views here.

def blog(request):
    post = Post.objects.all()

    context = {
        'posts':post
    }
    return render(request, 'post/index.html', context)

def blog_details(request, slug):
    post = Post.objects.get(slug=slug)
  

    context = {
       'post':post
    }
    return render(request, 'post/details/details.html', context)

myapp/views.py
from django.shortcuts import render
from.models import Profile

# Create your views here.

def homepage(request):
    profile = Profile.objects.all()

    context = {
        'profiles':profile
    }
    return render(request, 'index.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Bangladesh
</body>
</html>

templates/post/details/details.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static '/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static '/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Carousel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

<main class="mt-5">

    <div class="blog-single gray-bg">
        <div class="container">
            <div class="row align-items-start">
                <div class="col-lg-8 m-15px-tb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="{%url 'Blog:blog' %}">Home</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Delails</li>
                        </ol>
                      </nav>

          {% if messages %}
          {% for message in messages %}
                    
          <div class="alert alert-{{message.tags}}" role="alert">
           {{message}}
          </div>
          
          
          
          
          {% endfor %}
          {% endif %}
        
                
                    <article class="article">
                        <div class="article-img">
                            <img class="rounded" src="{{post.thumbnail.url}}" title="" alt="">
                        </div>
                        <div class="article-title">

                            <h2>{{post.title}}</h2>

                        </div>

                        <div class="article-content">

                          {{ post.description}}

                        </div>
                  
                    </article>
    
                </div>
        </div>
    </div>
    
        <div class="end">
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav">
                    <li class="nav-item"> <a class="nav-link" href="#" data-abc="true">Work</a> </li>
                    <li class="nav-item"> <a class="nav-link" href="#" data-abc="true">Capabilities</a> </li>
                    <li class="nav-item "> <a class="nav-link" href="#" data-abc="true">Articles</a> </li>
                    <li class="nav-item active"> <a class="nav-link mt-2" href="#" data-abc="true" id="clicked">Contact<span class="sr-only">(current)</span></a> </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Main Body -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-5 col-md-6 col-12 pb-4">
                    <h1>Comments</h1>

                        <h4>Jhon Doe</h4> <span>- 20 October, 2018</span> <br>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>
                    </div>

                </div>
                <div class="col-lg-8 col-md-8 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
                    <form id="algin-form"action='.'method='POST'>
                        <div class="form-group">
                            <h4>Leave a comment</h4> <label for="message">Message</label> <textarea name="body" id="" msg cols="30" rows="5" class="form-control"></textarea>
                        </div>
                        <div class="form-group"> <label for="name">Name</label> <input type="text" name="name" id="fullname" class="form-control"> </div>

                        <div class="form-group">
                            <p class="text-secondary">If you have a <a href="#" class="alert-link">gravatar account</a> your address will be used to display your profile picture.</p>
                        </div>
                      {% csrf_token %}
                        <div class="form-group"> <button class='btn btn-primary' type="button" id="post" class="btn">Post Comment</button> </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% for comment in comments %}
    <div class="bg-white p-2">
      <div class="d-flex flex-row user-info"><img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
          <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name">{{comment.name}}</span><span class="date text-black-50">{{ comment.creation | timesince }}</span></div>
      </div>
      <div class="mt-2">
          <p class="comment-text">{{comment.body}}</p>
      </div>
  </div>
  {% endfor %}

  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <script src="{% static '/assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>

templates/post/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static '/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static '/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Carousel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

<main class="mt-5">

  


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  {% for post in posts%}

  <div class=" container marketing">

    <!-- START THE FEATURETTES -->

 

    <div   class="row featurette d-flex align-items-center">
      <div class="col-md-6">
        <h2 class="featurette-heading">{{ post.title }}</h2>
        <p class="lead">{{ post.short_description }}</p>
        <p class="lead">{{ post.created_at |timesince }} ago</p>
        <a href="{{post.get_absolute_url}}"><button class="btn btn-primary">view detals</button></a>
      </div>
      <div class="col-md-6">
        <img class="rounded" src="{{ post.thumbnail.url }}" alt="">

      </div>
    </div>
    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->
  {% endfor %}


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <script src="{% static '/assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>